export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/store-list/store-list',
    'pages/store-detail/store-detail',
    'pages/stylist-detail/stylist-detail',
    'pages/appointment/select-store',
    'pages/appointment/select-stylist',
    'pages/appointment/select-service',
    'pages/appointment/select-time',
    'pages/appointment/confirm-order',
    'pages/order/order-list',
    'pages/member/member-center',
    'pages/coupon/coupon-list',
    'pages/points-mall/points-mall',
    'pages/ai-hairstyle/ai-hairstyle',
    'pages/messages/messages',
    'pages/profile/profile',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFFFFF',
    navigationBarTitleText: 'HairCut',
    navigationBarTextStyle: 'black',
    backgroundColor: '#F7F8FA',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#C8A882',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/icons/home.png',
        selectedIconPath: 'assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/store-list/store-list',
        text: '门店',
        iconPath: 'assets/icons/store.png',
        selectedIconPath: 'assets/icons/store-active.png',
      },
      {
        pagePath: 'pages/appointment/select-store',
        text: '预约',
        iconPath: 'assets/icons/appointment.png',
        selectedIconPath: 'assets/icons/appointment-active.png',
      },
      {
        pagePath: 'pages/order/order-list',
        text: '订单',
        iconPath: 'assets/icons/order.png',
        selectedIconPath: 'assets/icons/order-active.png',
      },
      {
        pagePath: 'pages/profile/profile',
        text: '我的',
        iconPath: 'assets/icons/profile.png',
        selectedIconPath: 'assets/icons/profile-active.png',
      },
    ],
  },
});
